name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CR_TOKEN: ${{ secrets.CR_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Prepare image tag
      run: |
        echo "IMAGE_TAG=ghcr.io/importnil/neovim:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG
    - name: Push the Docker image
      run: echo $CR_TOKEN | docker login ghcr.io -u importnil --password-stdin && docker push $IMAGE_TAG
